name: LIB VECTOR CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: build lib
        run: make

  test:
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker
    steps:
      - uses: actions/checkout@v4
      - name: build and run tests
        run: make tests_run

  asan_tests:
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker
    steps:
      - uses: actions/checkout@v4
      - name: Update LLVM
        run: |
          apt-get install -y llvm-16 clang-16
      - name: build and run tests with clang address sanatiser
        run: make asan_tests
